/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_myndkceshi_HelloJni */

#ifndef _Included_com_example_administrator_myndkceshi_HelloJni
#define _Included_com_example_administrator_myndkceshi_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_myndkceshi_HelloJni
 * Method:    HelloWord
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_administrator_myndkceshi_HelloJni_HelloWord
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
